#!/usr/bin/env node

const rollup = require('rollup').rollup;
const babel = require('rollup-plugin-babel');

rollup({
  entry: 'index.js',
  external: ['acorn', 'magic-string', 'rollup-pluginutils', 'rollup', 'vm', 'assert'],
  plugins: [babel()]
}).then(bundle => {
  bundle.write({
    dest: 'dist/rollup-plugin-stub.es6.js',
    format: 'es6'
  });
  bundle.write({
    dest: 'dist/rollup-plugin-stub.cjs.js',
    format: 'cjs'
  });
});
